<script setup>
const props = defineProps(['lang', 'resume_config']); 
</script>
<template>
  <main>
    <HeaderComponent :config="resume_config" :lang="lang"/>
    <ExperiencesComponent 
      v-if="resume_config.resume_sections['experiences']" 
      :lang="lang"
      :translations="resume_config[lang]['experiences']"
    />
    <EducationComponent 
      v-if="resume_config.resume_sections['education']" 
      :lang="lang"
      :translations="resume_config[lang]['education']"
    />
    <ProjectsComponent 
      v-if="resume_config.resume_sections['projects']" 
      :lang="lang"
      :translations="resume_config[lang]['projects']"
    />
    <SkillsComponent 
      v-if="resume_config.resume_sections['skills']" 
      :lang="lang"
      :translations="resume_config[lang]['skills']"
    />
    <RecognitionsComponent 
      v-if="resume_config.resume_sections['recognitions']" 
      :lang="lang"
      :translations="resume_config[lang]['recognitions']"
    />
    <AssociationsComponent 
      v-if="resume_config.resume_sections['associations']" 
      :lang="lang"
      :translations="resume_config[lang]['associations']"
    />
    <LinksComponent 
      v-if="resume_config.resume_sections['links']" 
      :lang="lang"
      :translations="resume_config[lang]['links']"
    />
  </main>
</template>
